Repository truenas/charts, pull requests merged in 2023-03, with the labels that each got.

#1009 NAS-120551 / 23.10 / Plex: Set hostNetwork value in both true/false cases
  charts/plex/1.7.30/.helmignore
  charts/plex/1.7.30/Chart.lock
  charts/plex/1.7.30/Chart.yaml
  charts/plex/1.7.30/README.md
  charts/plex/1.7.30/app-readme.md
  charts/plex/1.7.30/charts/common-2207.0.0.tgz
  charts/plex/1.7.30/default_values.yaml
  charts/plex/1.7.30/ix_values.yaml
  charts/plex/1.7.30/migrations/migrate_from_1.0.0
  charts/plex/1.7.30/questions.yaml
  charts/plex/1.7.30/templates/NOTES.txt
  charts/plex/1.7.30/templates/deployment.yaml
  charts/plex/1.7.30/templates/probe_config.yaml
  charts/plex/1.7.30/templates/service-tcp.yaml
  charts/plex/1.7.30/templates/service-udp.yaml
  charts/plex/1.7.30/templates/tests/deployment-check.yaml
  charts/plex/1.7.30/test_values.yaml
  test/plex/1.7.30/.helmignore
  test/plex/1.7.30/Chart.lock
  test/plex/1.7.30/Chart.yaml
  test/plex/1.7.30/README.md
  test/plex/1.7.30/app-readme.md
  test/plex/1.7.30/charts/common-2207.0.0.tgz
  test/plex/1.7.30/default_values.yaml
  test/plex/1.7.30/ix_values.yaml
  test/plex/1.7.30/migrations/migrate_from_1.0.0
  test/plex/1.7.30/questions.yaml
  test/plex/1.7.30/templates/NOTES.txt
  test/plex/1.7.30/templates/deployment.yaml
  test/plex/1.7.30/templates/probe_config.yaml
  test/plex/1.7.30/templates/service-tcp.yaml
  test/plex/1.7.30/templates/service-udp.yaml
  test/plex/1.7.30/templates/tests/deployment-check.yaml
  test/plex/1.7.30/test_values.yaml
Labels: bug, jira

#1024 NAS-120624 / 23.10 / Add recommended apps yaml file
  recommended_apps.yaml
Labels: skip jira status

#1023 NAS-120628 / 23.10 / Add IPFS app to community train
  library/ix-dev/community/ipfs/Chart.lock
  library/ix-dev/community/ipfs/Chart.yaml
  library/ix-dev/community/ipfs/README.md
  library/ix-dev/community/ipfs/app-readme.md
  library/ix-dev/community/ipfs/charts/common-1.0.0.tgz
  library/ix-dev/community/ipfs/ci/basic-values.yaml
  library/ix-dev/community/ipfs/ci/extra-env-values.yaml
  library/ix-dev/community/ipfs/ci/hostNet-values.yaml
  library/ix-dev/community/ipfs/item.yaml
  library/ix-dev/community/ipfs/questions.yaml
  library/ix-dev/community/ipfs/templates/NOTES.txt
  library/ix-dev/community/ipfs/templates/_configuration.tpl
  library/ix-dev/community/ipfs/templates/_ipfs.tpl
  library/ix-dev/community/ipfs/templates/_portal.tpl
  library/ix-dev/community/ipfs/templates/common.yaml
  library/ix-dev/community/ipfs/upgrade_strategy
  library/ix-dev/community/ipfs/values.yaml
Labels: jira

#1040 NAS-121113 / 23.10 / Retire charts deploy action
  .github/workflows/deploy_charts.yml
Labels: jira, skip jira status

#1059 NAS-121182 / 23.10 / Use tcpSocket probe for plex, as we determine if plex is setup to use HTTPS or HTTP
  library/ix-dev/charts/plex/Chart.yaml
  library/ix-dev/charts/plex/templates/deployment.yaml
Labels: jira

#1057 NAS-121181 / 23.10 / Use a noauth endpoint for syncthing probe
  library/ix-dev/charts/syncthing/Chart.yaml
  library/ix-dev/charts/syncthing/templates/deployment.yaml
Labels: jira
